Update Dockerfile
fatal error: limits.h: No such file or directory
fatal error: ffi.h: No such file or directory
The 'make' utility is missing from PATH
fatal error: openssl/opensslv.h: No such file or directory
fatal error: linux/tipc.h: No such file or directory